name: aumigos_da_vizinhanca
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.1
  flutter_animate: ^4.4.1
  page_transition: ^2.1.0
  image_picker: ^1.0.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.5
  internet_connection_checker: ^1.0.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  uuid: ^4.3.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.1.2
  # timezone: ^0.9.3
  # flutter_native_timezone: 

  provider: ^6.1.2
  intl: ^0.19.0
  # flutter_timezone: ^1.0.8

flutter_native_splash:
  color: "#FFC828"
  image: "images/aumigos_da_vizinhanca_logo_splash_screen.png"
  android: true
  ios: true

flutter_icons:
  image_path: "images/aumigos_da_vizinhanca_app_icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
